### ISSUE TITLE
Uncaught TypeError: node.getAttribute is not a function

### ISSUE THREAD

**Issue by backit** [stuartlangridge/sorttable#30]
Hi, thanks for this amazing library!
the firefox console report this error:
Uncaught TypeError: node.getAttribute is not a function
    getInnerText http://mydomain.com/static/js/sorttable.js:211
    getInnerText http://mydomain.com/static/js/sorttable.js:236
    guessType http://mydomain.com/static/js/sorttable.js:170
    makeSortable http://mydomain.com/static/js/sorttable.js:87
    init http://mydomain.com/static/js/sorttable.js:36
    forEach http://mydomain.com/static/js/sorttable.js:453
    forEach http://mydomain.com/static/js/sorttable.js:492
    init http://mydomain.com/static/js/sorttable.js:34

firefox 86
kubuntu 18.04.5

Best regards

**Comment by doublechiang** [comment]
Strange, I used exactly the same javascript in my 2 different projects. One has the problem while the other one has this issue. I have no idea why still working on it.

**Comment by doublechiang** [comment]
I found my problem.
The table I used has non-text <td> element. I embedded a form in the TD area, so it can't a valid innerText object.
```
      <td>
        <form method="post" action="<%= url_for '/' + inv.id.to_s %>" id="delete_inv">
        <input type="hidden" name="_method" value="delete">
        <button type="submit">Delete</button>
        </form>
      </td>
```

I don't need this column to be sorted, so I just add a `<th class="sorttable_nosort">Action</th>` to resolve this issue.

**Comment by shawnkhall** [comment]
@doublechiang Another option would be to update your sorttable.js to the one from the master branch. The node.getAttribute issue (as well as several other bugs) are fixed there.

**Comment by backit** [comment]
Confirm issue was due to @doublechiang  same problem.
Checked new master version solves this. 
Thanks.
