### ISSUE TITLE
ES6 rewrite

### ISSUE THREAD

**Issue by avindra** [stuartlangridge/sorttable#7]
Hi Stuart,

Thanks for sorttable.

It is a very useful library we use in our projects at work.

Do you have any interest in rewriting it with ES6 ? I did this partially so we can use the library more efficiently.

I can submit a PR if you would check it out.

**Comment by stuartlangridge** [comment]
Do I have interest in doing it? Yes. Do I have time right now? No, sadly :( There are various things I'd like to rewrite in a new version of sorttable. (I probably wouldn't port to full ES6, though; sorttable working across browsers and back to older browsers is a valuable property I wouldn't want to break.)

**Comment by avindra** [comment]
> working across browsers and back to older browsers is a valuable property I wouldn't want to break.

Noted. thanks for a great table library. My personal hell is the modern stuff like [react-bootstrap-table](https://github.com/AllenFang/react-bootstrap-table). Render times of over 4 seconds between updates is not uncommon.
